name = "stockz"
main = "server/src/index.ts"
compatibility_date = "2025-03-21"
placement = { "mode" = "smart" }

[assets]
binding = "ASSETS"
directory = "./client/dist"
not_found_handling = "single-page-application"
